### ISSUE TITLE
SourceKit-LSP does not work in VS Code

### ISSUE THREAD

**Issue by mkbrwr** [apple/swift-embedded-examples#46]
Code completions and jump to definition does not work for stm32-uart-echo example project
I can't get sourcekit-lsp to work in VS Code
Here's the error that shows up in Output view for SourceKit Language Server when I hover over words in `Application.swift`
```
[Error - 09:24:45] Request textDocument/hover failed.
  Message: sourcekitd request failed: error response (Request Failed): Loading the standard library failed
  Code: -32001 
```
AFAIU there isn't a swift standard library for embedded projects so the error is expected.
But is there a way to configure sourcekit-lsp so it that will work for this environment ?

**Comment by kubamracek** [comment]
https://github.com/apple/swift-embedded-examples/pull/47
