### ISSUE TITLE
SourceKit error: Cannot use metatype of type 'RCC.AHB1ENR.ReadWrite' in embedded Swift 

### ISSUE THREAD

**Issue by mkbrwr** [apple/swift-embedded-examples#48]
While the stm32-uart-echo builds successfully, there are errors from SourceKit. Here's one of them 
<img width="894" alt="Screenshot 2024-08-10 at 11 54 13" src="https://github.com/user-attachments/assets/d68c6e8e-a781-4de2-8f46-e4019d111180">

**Comment by kubamracek** [comment]
This is a false positive diagnostic coming from SourceKit, which is not present in regular builds, because regular builds have WMO (as required by Embedded Swift), but SourceKit sidesteps that and runs PerfDiags without WMO.

**Comment by kubamracek** [comment]
I think this should address it: https://github.com/swiftlang/swift/pull/75308

**Comment by kubamracek** [comment]
Tried the latest downloadable toolchain and verified this is fixed now.
